import { FinanceStateData } from "../models/finance-state-data";

export const FINANCIAL_STATE_DATA_MOCKUP: FinanceStateData = {
  incomes: { age: 23, employment: 17000, expenses: 7500, homeOwner: "false", investment: 0, other: 0, rent: 0 },
  financialAssets: {
    bank: 500,
    bankCR: 0,
    bonds: 0,
    bondsCR: 0,
    cash: 35,
    cashCR: 0,
    crypto: 1050,
    cryptoCR: 15,
    emergencyFund: 1000,
    emergencyFundCR: 0,
    GIC: 0,
    GICCR: 0,
    gold: 0,
    goldCR: 0,
    other: 0,
    otherCR: 0,
    savings: 2100,
    savingsCR: 2,
    stocks: 0,
    stocksCR: 0,
    stocksDuration: "4",
  },
  physicalAssets: {
    electronics: 2500,
    electronicsCR: -15,
    equipment: 4000,
    equipmentCR: -15,
    other: 700,
    otherCR: 2,
    property: 0,
    propertyCR: 0,
    vehicle: 16000,
    vehicleCR: -15,
  },
  liabilities: {
    carLoan: 15000,
    carLoanCR: 1,
    carLoanMP: 190,
    creditCard: 0,
    creditCardCR: 0,
    creditCardMP: 0,
    creditLine: 0,
    creditLineCR: 0,
    creditLineMP: 0,
    medicalDebt: 0,
    medicalDebtCR: 0,
    medicalDebtMP: 0,
    mortgage: 0,
    mortgageCR: 0,
    mortgageMP: 0,
    other1: 400,
    other1CR: 0,
    other1MP: 80,
    other2: 0,
    other2CR: 0,
    other2MP: 0,
    other3: 0,
    other3CR: 0,
    other3MP: 0,
    personalLoan: 0,
    personalLoanCR: 0,
    personalLoanMP: 0,
    studentLoan1: 5000,
    studentLoan1CR: 1.43,
    studentLoan1MP: 340,
    studentLoan2: 0,
    studentLoan2CR: 0,
    studentLoan2MP: 0,
  },
};
